### ISSUE TITLE
Session start time is not getting saved correctly

### ISSUE THREAD

**Issue by jorgeatorres** [WordPress/wordcamp.org#558] opened 2020-08-22 15:19 UTC
**Describe the bug**

After editing time information for any session on [our WordCamp site](https://colombia.wordcamp.org/2020/), the start time doesn't get updated on the schedule or the list of posts (on the backend).

Initially [reported in Slack](https://wordpress.slack.com/archives/C08M59V3P/p1598107426068400).

**To reproduce**

1. Go to 'Sessions' on the backend.
2. Click on any session or add a new one.
3. Set or change the session time information (date & length).
4. Save the post.
5. Go back to the list of posts or to the schedule (a page using the schedule block) and see that the time isn't correct: length is but start time doesn't reflect the new one.
  In the case of a newly created session post, the session doesn't even appear as the start time "seems" to be blank.
6. Try to edit the session post again and see that, weirdly, the correct time info does appear here.

**Expected behavior**

Session times to be correctly updated sitewide.

**Screenshots**

Screencast illustrating the problem: https://d.pr/i/P8Gx0P

**WordCamp**

https://colombia.wordcamp.org/2020/

**System (please complete the following information):**

 - Device: Laptop
 - OS: macOS 10.15.6
 - Browser: Chrome
 - Version: 84.0.4147.135

**Comment by rocket-martue** [comment] 2020-08-24 15:05
After August 21, when we edit the time information for any session on the WordCamp site, the value will be saved in Link to slides.

**Comment by ryelle** [comment] 2020-08-24 16:29
Thanks for reporting this.

This was fixed with https://github.com/WordPress/wordcamp.org/commit/257773969d6ebb381a075b397d706e50dff8d09e, caused by an issue introduced in #512.

**Closed as completed by ryelle** 2020-08-24 16:29 UTC
Labels: [Type] Bug, [Component] WC-Post-Types
