### ISSUE TITLE
Sponsor Invoices: Emails only go to Invoice requestor

### ISSUE THREAD

**Issue by CdrMarks** [WordPress/wordcamp.org#708] opened 2021-11-14 19:55 UTC
**Describe the bug**

Emailed noticed about the generation and payment of invoices are only sent to the user that created the invoice.

**To reproduce**

1. As a WordCamp site user, create an invoice
2. Have Harmony or someone with her capabilities approve or issue an invoice
3. Receive an email at the email address associated with the invoice requestor

**Expected behavior**

I was expecting these notices to be sent to the WordCamp site's Administration Email Address

**Comment by iandunn** [comment] 2021-11-15 17:29
That's the intended behavior, rather than a bug:

https://github.com/WordPress/wordcamp.org/blob/055fd1a66f036da5211ba489dc80a65e3d3a8081/public_html/wp-content/plugins/wordcamp-payments-network/includes/sponsor-invoices-dashboard.php#L357

It makes sense to me that the person who created the invoice would be the one who manages the rest of the process for it, but I'm guessing you use a different workflow?

Or is the goal to have the notices archived in a shared email box that is linked to the site admin address?

Maybe CC'ing the site admin address would solve this use case without disrupting other workflows where the author expects to get it directly?

**Comment by CdrMarks** [comment] 2021-11-15 20:45
I opened this as a bug since I could only find these emailed notices in the email mailbox tied to my WPORG account, but I expected to see them in the shared WordCamp Google account we have.

Should I close this and reopen as a feature request?

**Comment by iandunn** [comment] 2021-11-15 21:44
No, it's totally fine like this, I just mentioned that to help frame the discussion as _adding_ support for this use case, rather than _replacing_ the current behavior.

**Comment by CdrMarks** [comment] 2021-12-10 20:25
I know this is still open and I've not had a chance to submit a PR for it yet.

Adding a note that I happened to see an email generated by  [send_invoice_pending_reminder_mail( $invoice_id, $organizer_mail )](https://github.com/WordPress/wordcamp.org/blob/055fd1a66f036da5211ba489dc80a65e3d3a8081/public_html/wp-content/plugins/wordcamp-payments-network/includes/sponsor-invoices-dashboard.php#L581) which was also only sent to the user the created the sponsor.  It's interesting, though, that this email's salutation was, "Howdy organizers".

**Comment by timiwahalahti** [comment] 2023-07-29 04:48
Related #641

**Comment by kcristiano** [comment] 2023-09-13 18:35
Just noting the issue was mentioned today - https://wordpress.slack.com/archives/C04L4HPFGHX/p1694624631633049

Email is not 100% so we'll always need copies.  Organizing teams sometimes have Orgs that leave so linking to the creator's email is less than optimal.   I do think an improvement would be to send them to the camps city@wordcamp.org email.

Next steps might include storing invoice number  in the CPT that would let Organizers know it was generated and give those who can get copies a quicker way to find them.  

If we can also open another ticket about allowing download by the organizers That would be very helpful.   As these are transactional in nature, I don't really see any issues with WC admins being able to do that.  

Before I look at the next steps I'd like to get this issue closed as wontfix or adopted.

**Comment by timiwahalahti** [comment] 2023-09-21 18:14
> Next steps might include storing invoice number in the CPT that would let Organizers know it was generated and give those who can get copies a quicker way to find them.

On the invoice post, there actually should already be a link to QBO for super deputies.

**Comment by kcristiano** [comment] 2023-09-22 17:01
@timiwahalahti Is the link working?  Wouldn't all super deputies need QBO access?   @harmonyromo   Can we (or did we) set up View only access in QBO?

**Comment by harmonyromo** [comment] 2023-09-22 19:36
I think the only "viewing" user role would be just to see reports. There are other specific ones related to bill payment and expenses, but that wouldn't help here. I will do a bit more digging into this to be sure.

**Comment by timiwahalahti** [comment] 2023-09-23 19:49
The link works for people with QBO access. Deputies being able to see invoice numbers might help sometimes, even though they cannot see the invoice or access QBO itself(?). Saving the invoice number and showing it would be the first step for #1060.

**Closed as completed** 2023-10-09 20:55 UTC
Labels: [Component] Payments
