### ISSUE TITLE
Bring QR code to the camptix attendance addon

### ISSUE THREAD

**Issue by evrpress** [WordPress/wordcamp.org#1439] opened 2024-12-10 15:20 UTC
### Components / Tools

Attendance UI

### Description

Most of us know how atteendes are check-in on WordCamp. Ask for the name and search in the interface for the hopefully correct spelled name. Once you find the person and marked their check-in status, three new people lined up already.

**This is why I propose a QR Scanner in the [Attendance Addon](https://github.com/WordPress/wordcamp.org/tree/production/public_html/wp-content/plugins/camptix-attendance)**

The idea is that anyone with the "secret Link" from the "Attendance UI" settings page can use the QR scanner with their modern Smartphone or a laptop with an attached webcam.

People approach the check-in and our team scans their QR codes to check them in

### Screenshots / Screencasts

I made a quick prototype to illustrate my idea:

https://github.com/user-attachments/assets/b0d47568-81ca-4fab-9a26-46567e4585cb

### Stakeholders

I think everyone who worked at the registration desk knows how people queue up quickly and processing attendes faster is always a good improvements to WordCamps.

### How does this new feature contribute to the goals

**Think through it, what is the ultimate goal you hope this feature will achieve?** Explain.

Make the check-in process smoother for all

**Are there other more intuitive alternative solutions?** Explain.

My solution is based on the existing system which is used for smaller WordCamps (personally used in WCNL and WCVienna). Extending this so people can optionally 

**Is this a feature that people need?** Explain.

[Yes](https://github.com/WordPress/wordcamp.org/issues/613), I [guess](https://make.wordpress.org/community/2019/07/07/proposal-qr-code-for-wordcamp-badges/) so

**Can it truly achieve your desired outcomes?** Explain.

Not yet, It's by far not finished but I need a starting point and more feedback

### Acceptance Criteria

1) The current "experience" should not change (with this feature) so people can work how they did before.
2) The feature should work on smartphones so check-in can be done by more people during rush hours.

### Priority

I'm helping organize WCVienna in April next year and would love to work with that.

Since I see a lot of contributions from @iandunn I'm ping him here.

**Comment by pkevan** [comment] 2024-12-10 16:46
Seems like a good idea.

>The idea is that anyone with the "secret Link" from the "Attendance UI" settings page can use the QR scanner with their modern Smartphone or a laptop with an attached webcam.

I think we should avoid any secret link, and work on a UI which is behind user authentication (probably administrator level) for this.

It would also be good to hear from any flag-ship events who use external providers for generating QR codes, to see if we can solve than reliance as well.

**Comment by evrpress** [comment] 2024-12-10 17:01
The secret link exists already and is used. Adding authentication (with a valid reason) brings more complexity and should be solved on a higher level.

I see no point why using an external provider for QR codes. They can be generated with PHP or an API call. The code itself should be somewhat non-identifiable. I used the md5 hash of the access token.

**Comment by dd32** [comment] 2024-12-11 00:28
This is a duplicate of #613 where work has been done in the past, which is linked in this ticket too, so I'm not sure why you felt the need to create a new Issue - Please feel free to work on the older ticket.

**Closed as not planned by dd32** 2024-12-11 00:28 UTC
Labels: [Type] Feature Request
